# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/josei/Final_Project/Final_Project.srcs/sources_1/ip/game_background_rom/game_background_rom.xci
# IP: The module: 'game_background_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/josei/Final_Project/Final_Project.gen/sources_1/ip/game_background_rom/game_background_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_background_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/josei/Final_Project/Final_Project.srcs/sources_1/ip/game_background_rom/game_background_rom.xci
# IP: The module: 'game_background_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/josei/Final_Project/Final_Project.gen/sources_1/ip/game_background_rom/game_background_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'game_background_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
